# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 0
  minor: 0
  patch: $(Build.BuildID)
  buildVer: $(major).$(minor).$(Build.BuildID)

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $buildVersion = $env:BUILDVER
      $manifestPath = Join-Path -Path $env:SYSTEM_DEFAULTWORKINGDIRECTORY -ChildPath "AzLandingZone/AzLandingZone.psd1"
      $manifestContent = Get-Content -Path $manifestPath -Raw
      $manifestContent = $manifestContent -replace '<ModuleVersion>', $buildVersion
      $manifestContent | Set-Content -Path $manifestPath
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '$(System.DefaultWorkingDirectory)/AzLandingZone/AzLandingZone.nuspec'
    versioningScheme: byEnvVar
    versionEnvVar: buildVer
    buildProperties: 'VERSIONHERE=$(buildVer)'

- task: NuGetCommand@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '6414d3a7-f802-4703-8cd7-9cef7c9a9617/70f7f03a-51ae-4735-891b-045a34d1d29e'
- task: NuGetCommand@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '6414d3a7-f802-4703-8cd7-9cef7c9a9617/6a3c56f7-797c-4a29-b562-75b5178170f0'
- task: AzurePowerShell@5
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  inputs:
    azureSubscription: 'SECLOG_EC_DIGIT_TEST_LZ(689da1ad-9d2d-46f7-9daa-1e02008702ba)'
    ScriptType: 'InlineScript'
    Inline: |
      Register-PSRepository -Name "AzLandingZoneRepo" -SourceLocation "https://pkgs.dev.azure.com/devops0837/LandingZonePublic/_packaging/developmentfeed/nuget/v2 " -publishLocation "https://pkgs.dev.azure.com/devops0837/LandingZonePublic/_packaging/developmentfeed/nuget/v2"
      Install-Module -Force -Name "AzLandingZone" -Repository "AzLandingZoneRepo"
      Import-Module AzLandingZone    
      New-AzLandingZone -SOC "DIGIT" -autoupdate $false -location "westeurope" -enableEventHub $true -securityContact "augustin.colle@outlook.com" -retentionPeriod 365
    azurePowerShellVersion: 'LatestVersion'