# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ develop, master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pack:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: update version in psd file
      env: 
        major: 0
        minor: 0
        patch: 1
        buildVer: ${{ env.patch }}
      shell: pwsh
      run: |
        $buildVersion = ${{ env.buildVer }}
        $manifestPath = Join-Path -Path "$env:GITHUB_WORKSPACE" -ChildPath "AzLandingZone/AzLandingZone.psd1"
        $manifestContent = Get-Content -Path $manifestPath -Raw
        $manifestContent = $manifestContent -replace '<ModuleVersion>', "0.0.1"
        $manifestContent | Set-Content -Path $manifestPath
    
    - name: update version in nuspec file
      env: 
        major: 0
        minor: 0
        patch: 1
        buildVer: ${{ env.patch }}
      shell: pwsh
      run: |
        $buildVersion = ${{ env.buildVer }}
        $manifestPath = Join-Path -Path "$env:GITHUB_WORKSPACE" -ChildPath "AzLandingZone/AzLandingZone.nuspec"
        $manifestContent = Get-Content -Path $manifestPath -Raw
        $manifestContent = $manifestContent -replace 'VERSIONHERE', "0.0.1"
        $manifestContent | Set-Content -Path $manifestPath

    - name: setup NuGet
      uses: nuget/setup-nuget@v1
        
    - name: nuget pack
      run: nuget pack AzLandingZone/AzLandingZone.nuspec

    - name: Authenticate
      run: dotnet nuget add source https://nuget.pkg.github.com/digitc1/ -n github -u digitc1 -p GITHUB_TOKEN --store-password-in-clear-text
      
    - name: push
      run: dotnet nuget push "**.nupkg" --source "github" -k GITHUB_TOKEN
      
    - name: nuget push for develop
      if: ${{ success() && github.ref == 'refs/heads/develop' }}
      run: nuget push "AzLandingZone.0.0.1.nupkg" -Source "GitHub"

    - name: nuget push for master
      if: ${{ success() && github.ref == 'refs/heads/master' }}
      run: nuget push AzLandingZone/AzLandingZone.nuspec
