# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ develop, master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pack:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
        
    - name: nuget pack        
      run: nuget pack AzLandingZone/AzLandingZone.nuspec

    - name: nuget push for develop
      if: ${{ success() && github.ref == 'refs/heads/develop' }}
      run: nuget push AzLandingZone/AzLandingZone.nuspec

    - name: nuget push for master
      if: ${{ success() && github.ref == 'refs/heads/master' }}
      run: nuget push AzLandingZone/AzLandingZone.nuspec
